export const departamentos = [ 
    {"dptoCode": "01","nombre": "Amazonas"},
    {"dptoCode": "02","nombre": "Ancash"},
    {"dptoCode": "03","nombre": "Apurimac"},
    {"dptoCode": "04","nombre": "Arequipa"},
    {"dptoCode": "05","nombre": "Ayacucho"},
    {"dptoCode": "06","nombre": "Cajamarca"},
    {"dptoCode": "07","nombre": "Callao"},
    {"dptoCode": "08","nombre": "Cusco"},
    {"dptoCode": "09","nombre": "Huancavelica"},
    {"dptoCode": "10","nombre": "Huanuco"},
    {"dptoCode": "11","nombre": "Ica"},
    {"dptoCode": "12","nombre": "Junin"},
    {"dptoCode": "13","nombre": "La Libertad"},
    {"dptoCode": "14","nombre": "Lambayeque"},
    {"dptoCode": "15","nombre": "Lima"},
    {"dptoCode": "16","nombre": "Loreto"},
    {"dptoCode": "17","nombre": "Madre de Dios"},
    {"dptoCode": "18","nombre": "Moquegua"},
    {"dptoCode": "19","nombre": "Pasco"},
    {"dptoCode": "20","nombre": "Piura"},
    {"dptoCode": "21","nombre": "Puno"},
    {"dptoCode": "22","nombre": "San Martin"},
    {"dptoCode": "23","nombre": "Tacna"},
    {"dptoCode": "24","nombre": "Tumbes"},
    {"dptoCode": "25","nombre": "Ucayali"}
]
export const provincias = [
    {"dptoCode": "15","provCode": "01","nombre": "Lima"},
    {"dptoCode": "15","provCode": "02","nombre": "Barranca"},
    {"dptoCode": "15","provCode": "03","nombre": "Cajatambo"},
    {"dptoCode": "15","provCode": "04","nombre": "Canta"},
    {"dptoCode": "15","provCode": "05","nombre": "Cañete"},
    {"dptoCode": "15","provCode": "06","nombre": "Huaral"},
    {"dptoCode": "15","provCode": "07","nombre": "Huarochiri"},
    {"dptoCode": "15","provCode": "08","nombre": "Huaura"},
    {"dptoCode": "15","provCode": "09","nombre": "Oyon"},
    {"dptoCode": "15","provCode": "10","nombre": "Yauyos"},
    {"dptoCode": "10","provCode": "01","nombre": "Huanuco"},
    {"dptoCode": "10","provCode": "02","nombre": "Ambo"},
    {"dptoCode": "10","provCode": "03","nombre": "Dos de Mayo"},
    {"dptoCode": "10","provCode": "04","nombre": "Huacaybamba"},
    {"dptoCode": "10","provCode": "05","nombre": "Huamalies"},
    {"dptoCode": "10","provCode": "06","nombre": "Leoncio Prado"},
    {"dptoCode": "10","provCode": "07","nombre": "Marañon"},
    {"dptoCode": "10","provCode": "08","nombre": "Pachitea"},
    {"dptoCode": "10","provCode": "09","nombre": "Puerto Inca"},
    {"dptoCode": "10","provCode": "10","nombre": "Lauricocha"},
    {"dptoCode": "10","provCode": "11","nombre": "Yarowilca"}
]

export const distritos = [
    { "dptoCode": "15","provCode": "01", "distCode": "01", "nombre": "Lima" },
    { "dptoCode": "15","provCode": "01", "distCode": "02", "nombre": "Ancón" },
    { "dptoCode": "15","provCode": "01", "distCode": "03", "nombre": "Ate" },
    { "dptoCode": "15","provCode": "01", "distCode": "04", "nombre": "Barranco" },
    { "dptoCode": "15","provCode": "01", "distCode": "05", "nombre": "Breña" },
    { "dptoCode": "15","provCode": "01", "distCode": "06", "nombre": "Carabayllo" },
    { "dptoCode": "15","provCode": "01", "distCode": "07", "nombre": "Chaclacayo" },
    { "dptoCode": "15","provCode": "01", "distCode": "08", "nombre": "Chorrillos" },
    { "dptoCode": "15","provCode": "01", "distCode": "09", "nombre": "Cieneguilla" },
    { "dptoCode": "15","provCode": "01", "distCode": "10", "nombre": "Comas" },
    { "dptoCode": "15","provCode": "01", "distCode": "11", "nombre": "El Agustino" },
    { "dptoCode": "15","provCode": "01", "distCode": "12", "nombre": "Independencia" },
    { "dptoCode": "15","provCode": "01", "distCode": "13", "nombre": "Jesús María" },
    { "dptoCode": "15","provCode": "01", "distCode": "14", "nombre": "La Molina" },
    { "dptoCode": "15","provCode": "01", "distCode": "15", "nombre": "La Victoria" },
    { "dptoCode": "15","provCode": "01", "distCode": "16", "nombre": "Lince" },
    { "dptoCode": "15","provCode": "01", "distCode": "17", "nombre": "Los Olivos" },
    { "dptoCode": "15","provCode": "01", "distCode": "18", "nombre": "Lurigancho" },
    { "dptoCode": "15","provCode": "01", "distCode": "19", "nombre": "Lurin" },
    { "dptoCode": "15","provCode": "01", "distCode": "20", "nombre": "Magdalena del Mar" },
    { "dptoCode": "15","provCode": "01", "distCode": "21", "nombre": "Pueblo Libre" },
    { "dptoCode": "15","provCode": "01", "distCode": "22", "nombre": "Miraflores" },
    { "dptoCode": "15","provCode": "01", "distCode": "23", "nombre": "Pachacámac" },
    { "dptoCode": "15","provCode": "01", "distCode": "24", "nombre": "Pucusana" },
    { "dptoCode": "15","provCode": "01", "distCode": "25", "nombre": "Puente Piedra" },
    { "dptoCode": "15","provCode": "01", "distCode": "26", "nombre": "Punta Hermosa" },
    { "dptoCode": "15","provCode": "01", "distCode": "27", "nombre": "Punta Negra" },
    { "dptoCode": "15","provCode": "01", "distCode": "28", "nombre": "Rímac" },
    { "dptoCode": "15","provCode": "01", "distCode": "29", "nombre": "San Bartolo" },
    { "dptoCode": "15","provCode": "01", "distCode": "30", "nombre": "San Borja" },
    { "dptoCode": "15","provCode": "01", "distCode": "31", "nombre": "San Isidro" },
    { "dptoCode": "15","provCode": "01", "distCode": "32", "nombre": "San Juan de Lurigancho" },
    { "dptoCode": "15","provCode": "01", "distCode": "33", "nombre": "San Juan de Miraflores" },
    { "dptoCode": "15","provCode": "01", "distCode": "34", "nombre": "San Luis" },
    { "dptoCode": "15","provCode": "01", "distCode": "35", "nombre": "San Martín de Porres" },
    { "dptoCode": "10", "provCode": "01", "distCode": "01", "nombre": "Amarilis" },
    { "dptoCode": "10", "provCode": "01", "distCode": "02", "nombre": "Chinchao" },
    { "dptoCode": "10", "provCode": "01", "distCode": "03", "nombre": "Churubamba" },
    { "dptoCode": "10", "provCode": "01", "distCode": "04", "nombre": "Huanuco" },
    { "dptoCode": "10", "provCode": "01", "distCode": "05", "nombre": "Pillco Marca" },
    { "dptoCode": "10", "provCode": "01", "distCode": "06", "nombre": "Quisqui" },
    { "dptoCode": "10", "provCode": "01", "distCode": "07", "nombre": "San Francisco de Cayran" },
    { "dptoCode": "10", "provCode": "01", "distCode": "08", "nombre": "San Pedro de Chaulan" },
    { "dptoCode": "10", "provCode": "01", "distCode": "09", "nombre": "Santa Maria del Valle" },
    { "dptoCode": "10", "provCode": "01", "distCode": "10", "nombre": "Yarumayo" }
]

